In [2]:
import matplotlib.pyplot as plt
import numpy as np
from matplotlib.animation import FuncAnimation
import collections
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D
from mpl_toolkits import mplot3d
import time
import threading
    
%matplotlib tk

exp_data_record = []
qubit_h = []
qubit = [1+0j,0+0j]

# function to update the data
ctrl_in = []
read_in = []
read_out = []
pump_in = []
theta = 0
theta1 = 0
signal_range = 0.5
ms = 0 #measurement

#fig = plt.figure()
fig = plt.figure(figsize=(10,8), facecolor='#DEDEDE', tight_layout=True)

                   
#ブロッホ球の描写
u = np.linspace(0, 2 * np.pi, 100)
v = np.linspace(0, np.pi, 100)

sin_u = np.zeros(100)
cos_u = np.zeros(100)
sin_v = np.zeros(100)
cos_v = np.zeros(100)

for i in range(100):
    sin_u[i]=(np.sin(u[i]))
    cos_u[i]=(np.cos(u[i]))
    sin_v[i]=(np.sin(v[i]))
    cos_v[i]=(np.cos(v[i]))
    
x = 1 * np.outer(np.cos(u), np.sin(v))
y = 1 * np.outer(np.sin(u), np.sin(v))
z = 1 * np.outer(np.ones(np.size(u)), np.cos(v))

k = np.linspace(-np.pi, np.pi, 100)

l=np.zeros(100)
m=np.zeros(100)

for i in range(100):
    l[i] = np.sin(k[i])
    m[i] = np.cos(k[i])

def my_function(i):
    global theta1, signal_range, read_in, read_out, theta, m
    # input control
    
    input_sys_i.popleft()
    input_sys_q.popleft()
    if len(ctrl_in)>1:
        input_sys_i.append(ctrl_in[-1][1])
        input_sys_q.append(ctrl_in[-1][2])
    else:
        input_sys_i.append(0.0)
        input_sys_q.append(0.0)
        
    output_sys_i.popleft()
    output_sys_q.popleft()
    
    #input readout
    input_read.popleft()
    if len(read_in)>1:
        input_read.append(read_in[0][1])
        read_in = read_in[1:]
    else:
        input_read.append(0)
        read_in = []
    
    
    if len(read_out)>1:
        if read_out[-1][1]!=0:
            output_sys_i.append(read_out[0][1])
            output_sys_q.append(read_out[0][2])
            if theta<0.5:
                theta += 0.01
            read_out = read_out[1:]
            test = (2*((1-(read_in[0][1])**2)**.5)*read_out[0][1] + (4*(read_in[0][1]**2 - read_out[0][1]**2))**.5)/2
            print(test)
            
            if ms != 1:
                theta1 = theta * (-1)
            else:
                theta1 = theta    
        else:     
            output_sys_i.append(0)
            output_sys_q.append(0)
    else:
        output_sys_i.append(0.0)
        output_sys_q.append(0.0)
        read_out = []
        theta = theta1 = 0
        
    # clear axis
    ax1.cla()
    ax2.cla()
    ax3.cla()
    ax4.cla()
    
    ax1.set_title("Input Control Wave")
    ax2.set_title("Input Readout Wave")
    ax3.set_title("Output Readout Wave")
    ax4.set_title("Input JPA Pump")
    
    # plot input1
    ax1.plot(input_sys_i,color="blue")
    ax1.scatter(len(input_sys_i)-1, input_sys_i[-1],color="blue")
    #ax1.text(len(input_sys_i)-1, input_sys_i[-1]+2, "{}%".format(input_sys_i[-1]))
    ax1.set_ylim(-1,1)
    
    ax1.plot(input_sys_q,color="red")
    ax1.scatter(len(input_sys_q)-1, input_sys_q[-1],color="red")
    #ax1.text(len(input_sys_q)-1, input_sys_q[-1]+2, "{}%".format(input_sys_q[-1]))

    # plot input2
    ax2.plot(input_read,color="blue")
    ax2.scatter(len(input_read)-1, input_read[-1],color="blue")
    #ax1.text(len(input_sys_i)-1, input_sys_i[-1]+2, "{}%".format(input_sys_i[-1]))
    ax2.set_ylim(-1,1)

    # plot output
    ax3.plot(output_sys_i,color="blue")
    ax3.scatter(len(output_sys_i)-1, output_sys_i[-1],color="blue")
    #ax2.text(len(output_sys_i)-1, output_sys_i[-1]+2, "{}%".format(output_sys_i[-1]))
    ax3.set_ylim(-1,1)
    

    ax3.plot(output_sys_q,color="red")
    ax3.scatter(len(output_sys_q)-1, output_sys_q[-1],color="red")
   # ax2.text(len(output_sys_q)-1, output_sys_q[-1]+2, "{}%".format(output_sys_q[-1]))

    # plot jpa input
    
    jpa_pump.popleft()
    if len(pump_in)>1:
        jpa_pump.append(pump_in[-1])
    else:
        jpa_pump.append(0.0)
        
    ax4.plot(jpa_pump,color="blue")
    ax4.scatter(len(jpa_pump)-1,jpa_pump[-1],color="blue")
    #ax2.text(len(output_sys_i)-1, output_sys_i[-1]+2, "{}%".format(output_sys_i[-1]))
    ax4.set_ylim(-1,1)
    
    #time.sleep(1)
    ax5.set_box_aspect([1,1,1])

    #目盛りとラベル
    ax5.set_xlabel('X')
    ax5.set_ylabel('Y')
    ax5.set_zlabel('Z')
    ax5.set_xlim(-1,1)
    ax5.set_ylim(-1,1)
    ax5.set_zlim(-1,1)
    ax5.set_xticks([-1,-0.5,0,0.5,1])
    ax5.set_yticks([-1,-0.5,0,0.5,1])
    ax5.clear()  
    ax5.grid(None)
    ax5.plot_surface(x, y, z,  rstride=4, cstride=4, color='lightblue', linewidth=0, alpha=0.25)

    ax5.plot(sin_u,cos_u,0,color='gray',linewidth=1.2)
    ax5.plot(np.linspace(0,0,100),sin_u,cos_u,color='gray',linewidth=1.2)
    ax5.plot(sin_u,np.linspace(0,0,100),cos_u,color='gray',linewidth=.5)

    for i in range(-4,5,1):
        if i!=0:
            d = .25 * i
        s = ((1-d**2)**.5)
        ax5.plot(sin_u*s,cos_u*s,d,color='gray',linewidth=.3)
        ax5.plot(np.linspace(d,d,100),sin_u*s,cos_u*s,color='gray',linewidth=.3)
        #ax.plot(np.sin(u)*s,np.linspace(d,d,100),np.cos(u)*s,color='gray',linewidth=.3)
    
    if (len(exp_data_record) > 0):
        if (exp_data_record[-1][0] <= 1.00001):
            ax5.plot(exp_data_record[-1][0], exp_data_record[-1][1], exp_data_record[-1][2], "o", c="blue")
        else:
            ax5.plot(0, 0, 1, "o", c="blue") 
    else:
        ax5.plot(0, 0, 1, "o", c="blue")
    
    #Digital Signal Processing Graph
    theta2 = theta1+((np.random.rand()-0.5)**3)*1.5
    xa = np.cos(theta2)
    ya = np.sin(theta2)
    ax6.clear()
    ax6.set_title("Digital Signal Processing")
    ax6.plot(l,m,linestyle='dotted', color="gray")
    ax6.plot([0,xa],[0,ya], color="red")
    if len(pump_in)>1:
        if (pump_in[-1] != 0):
            if(signal_range>0.15):
                signal_range-=0.01
        else:
            if(signal_range<0.5):
                signal_range+=0.01
    cc = plt.Circle((xa,ya),signal_range,color="red")
    ax6.add_artist( cc ) 
    ax6.spines['left'].set_position('zero')
    ax6.spines['bottom'].set_position('zero') 
    ax6.plot(0.85,0.5,"o",color="orangered")  
    #ax6.text(0.5, 0.85, 'θ1')
    ax6.plot(0.85,-0.5,"o",color="deepskyblue")
    #ax6.text(0.85, 0.5, 'θ0')
    ax6.set_xlim(-1.5,1.5)
    ax6.set_ylim(-1.2,1.2)

    
    ax7.clear()
    ax7.set_title("Output Wave I-Q")
    xx = output_sys_i[-1]
    yy = output_sys_q[-1]
    cc2 = plt.Circle((xx,yy),0.2,color="red")
    ax7.add_artist( cc2 ) 
    ax7.spines['left'].set_position('zero')
    ax7.spines['bottom'].set_position('zero') 
    ax7.plot(0.85,0.5,"o",color="orangered")  
    ax7.plot(0.85,-0.5,"o",color="deepskyblue")
    ax7.set_xlim(-1.5,1.5)
    ax7.set_ylim(-1.2,1.2)
    
    # Info
    ax8.clear()
    textstr = 'Hamiltonian = ωa†a+α/2 a†a†aa \n|ψ> = \n[δ(p3)=0\n γ(p2)=0\n α(p0)='+'{:.3g}'.format(qubit[0])+'\n β(p1)='+'{:.3g}'.format(qubit[1])+']'
    ax8.text(0.3, 0.3, textstr)

# start collections with zeros
input_sys_i = collections.deque(np.zeros(100))
input_sys_q = collections.deque(np.zeros(100))
input_read = collections.deque(np.zeros(100))
output_sys_i  = collections.deque(np.zeros(100))
output_sys_q  = collections.deque(np.zeros(100))
output_read  = collections.deque(np.zeros(100))
jpa_pump = collections.deque(np.zeros(100))

# define and adjust figure
gs = fig.add_gridspec(4,4)
ax1 = fig.add_subplot(gs[0, 0:2], facecolor="white")
ax2 = fig.add_subplot(gs[1, 0:2], facecolor="white")
ax3 = fig.add_subplot(gs[2, 0:2], facecolor="white")
ax4 = fig.add_subplot(gs[3, 0:2], facecolor="white")
ax5 = fig.add_subplot(gs[0:2, 2:4], projection='3d')
ax6 = fig.add_subplot(gs[2, 2:3], facecolor="white")
ax7 = fig.add_subplot(gs[2, 3:4], facecolor="white")
ax8 = fig.add_subplot(gs[3, 2:4], facecolor="white")

#グリッドと最初の表示
ax5.view_init(elev = 17, azim = 12)
    

# animate
ani = FuncAnimation(fig, my_function, interval=50)
plt.show()

In [2]:
def plot_bloch(qubit):
    global qubit_h
    #角度をxyz座標に変換
    dmatrix = [[1,1],[1,1]]
    dmatrix[0][0] = qubit[0]*qubit[0].conjugate()
    dmatrix[1][1] = qubit[1]*qubit[1].conjugate()
    dmatrix[0][1] = qubit[0] * qubit[1].conjugate()
    dmatrix[1][0] = qubit[0].conjugate() * qubit[1]
    #print(qubit)
    #print(dmatrix[0][0] - dmatrix[1][1])
    exp_data_record.append([2*dmatrix[0][1].real, 2*dmatrix[1][0].imag, dmatrix[0][0] - dmatrix[1][1]])
    qubit_h.append(qubit)
    if len(qubit_h)>0:
        qubit_h = qubit_h[-1:]
        
def plot_data(input_wave):
    time = input_wave[0]
    i = input_wave[1]
    q = input_wave[2]
    ctrl_in.append([time,i,q])
    
def readout(output):
    global qubit
    time = output[0]
    inpt = output[1]
    i = output[2]
    q = output[3]
    read_in.append([time, inpt])
    read_out.append([time,i,q])
    
def measurement():    
    global ms,qubit
    r = np.random.random()
    if (r>qubit[0]**2):
        ms = 1
        zure = np.pi/4
    else:
        ms = 0
        zure = -np.pi/4
    print(ms)
    for i in range(60):
        inpt = np.sin(4*i*np.pi/30)
        a = i/60 * np.sin(4*i*np.pi/30 + zure)
        b = i/60 * np.cos(4*i*np.pi/30 + zure)
        out = [i, inpt, a, b]
        readout(out)
        #time.sleep(0.1)
        #time.sleep(0.1)
        
def simple_pulse():
    for i in range(53):
        if (i>=0 and i<52):
            if(i>=0 and i<26):    
                phi = 0
            else:
                phi = np.pi/2
            a = np.sin(phi+(i/26)*np.pi)
            b = np.cos(phi+(i/26)*np.pi)
            qubit = apply_gate(phi,1)
        else:
            a = b = 0
        plot_bloch(qubit)
        input_wave = [i, a, b]
        plot_data(input_wave)
        #qubit = apply_gate(0,1) #RX-gate
        #qubit = apply_gate(np.pi/2,1) #RY-gate
        time.sleep(0.1)
        
def long_pulse():
    for i in range(160):
        if (i>=0 and i<160-1):   
            phi = 0
            a = np.sin(phi+(i/26)*np.pi)
            b = np.cos(phi+(i/26)*np.pi)
            qubit = apply_gate(phi,1)
        else:
            a = b = 0
        plot_bloch(qubit)
        input_wave = [i, a, b]
        plot_data(input_wave)
        #qubit = apply_gate(0,1) #RX-gate
        #qubit = apply_gate(np.pi/2,1) #RY-gate
        time.sleep(0.1)
        
def x_gate():
    for i in range(27):
        if(i>=0 and i<26):
            phi = 0
            a = np.sin(phi+(i/26)*np.pi)
            b = np.cos(phi+(i/26)*np.pi)
            qubit = apply_xgate(1)
            plot_bloch(qubit)
        else:
            a=b=0
        input_wave = [i, a, b]
        plot_data(input_wave)
        time.sleep(0.05)
        
def y_gate():
    for i in range(27):
        if(i>=0 and i<26):
            phi = np.pi/2
            a = np.sin(phi+(i/26)*np.pi)
            b = np.cos(phi+(i/26)*np.pi)
            qubit = apply_ygate(1)
            plot_bloch(qubit)
        else:
            a=b=0
        input_wave = [i, a, b]
        plot_data(input_wave)
        time.sleep(0.05)

def z_gate():
    for i in range(27):
        if(i>=0 and i<26):
            phi = np.pi/4
            a = np.sin(phi+(i/26)*np.pi)
            b = np.cos(phi+(i/26)*np.pi)
            qubit = apply_zgate(1)
            plot_bloch(qubit)
        else:
            a=b=0
        input_wave = [i, a, b]
        plot_data(input_wave)
        time.sleep(0.05)

def h_gate():
    for i in range(40):
        if(i>=0 and i<13):
            phi = np.pi/4
            a = np.sin(phi+(i/26)*np.pi)
            b = np.cos(phi+(i/26)*np.pi)
            qubit = apply_zgate(1)
            plot_bloch(qubit)
        elif(i>=13 and i<26):
            phi = 0
            a = np.sin(phi+(i/26)*np.pi)
            b = np.cos(phi+(i/26)*np.pi)
            qubit = apply_xgate(1)
            plot_bloch(qubit)
        elif(i>=26 and i<39):
            phi = np.pi/4
            a = np.sin(phi+(i/26)*np.pi)
            b = np.cos(phi+(i/26)*np.pi)
            qubit = apply_zgate(1)
            plot_bloch(qubit)
        else:
            a=b=0
        input_wave = [i, a, b]
        plot_data(input_wave)
        time.sleep(0.1)
        
def apply_xgate(t):
    global qubit
    if len(qubit_h)>0:
        qubit=qubit_h[-1]
    qubit2 = [1+0j,0+0j]
    theta = np.pi * t/26
    U = [[np.cos(theta/2)+0j,-(np.sin(theta/2))*1j],[-(np.sin(theta/2))*1j,np.cos(theta/2)+0j]]
    qubit2[0] = U[0][0]*qubit[0] + U[0][1]*qubit[1]
    qubit2[1] = U[1][0]*qubit[0] + U[1][1]*qubit[1]
    return qubit2

def apply_ygate(t):
    global qubit
    if len(qubit_h)>0:
        qubit=qubit_h[-1]
    qubit2 = [1+0j,0+0j]
    theta = np.pi * t/26
    U = [[np.cos(theta/2)+0j,-np.sin(theta/2)+0j],[np.sin(theta/2)+0j,np.cos(theta/2)+0j]]
    qubit2[0] = U[0][0]*qubit[0] + U[0][1]*qubit[1]
    qubit2[1] = U[1][0]*qubit[0] + U[1][1]*qubit[1]
    return qubit2

def apply_zgate(t):
    global qubit
    if len(qubit_h)>0:
        qubit=qubit_h[-1]
    qubit2 = [1+0j,0+0j]
    theta = np.pi * t/26
    U = [[np.exp(-(theta/2)*1j)+0j,0+0j],[0+0j,np.exp((theta/2)*1j)+0j]]
    qubit2[0] = U[0][0]*qubit[0] + U[0][1]*qubit[1]
    qubit2[1] = U[1][0]*qubit[0] + U[1][1]*qubit[1]
    return qubit2

def apply_gate(phi,t):
    global qubit
    if len(qubit_h)>0:
        qubit=qubit_h[-1]
    qubit2 = [1+0j,0+0j]
    I = np.cos(phi)
    Q = np.sin(phi)
    theta = np.pi * t/26
    U = [[np.cos(theta/2)+0j,-Q*np.sin(theta/2)-I*(np.sin(theta/2))*1j],[Q*np.sin(theta/2)-I*(np.sin(theta/2))*1j,np.cos(theta/2)+0j]]
    qubit2[0] = U[0][0]*qubit[0] + U[0][1]*qubit[1]
    qubit2[1] = U[1][0]*qubit[0] + U[1][1]*qubit[1]
    return qubit2

def pump():
    global pump_in
    for i in range(128):
        if(i>=0 and i<127):
            phi = np.pi/2
            a = np.sin(phi+(i/26)*np.pi)
        else:
            a=0
        pump_in.append(a)
        time.sleep(0.05)

In [3]:
threading.Thread(target=simple_pulse).start()

C:\Users\nilton\anaconda3\lib\site-packages\matplotlib\cbook\__init__.py:1298: ComplexWarning: Casting complex values to real discards the imaginary part
  return np.asarray(x, float)


In [4]:
threading.Thread(target=h_gate).start()

In [5]:
threading.Thread(target=measurement).start()

1
0.42065338644769273
0.7646727112531194
0.963779316043476
0.9980220149068489
0.876540911680758
0.5749212322747671
0.1358114062507075
0.06590047360590279
0.44894912951075994
0.7704368366621642
0.9693703875118166
0.9186541563448338
0.7354707296372291
0.4744383288710969


C:\Users\nilton\AppData\Local\Temp\ipykernel_15336\3414973861.py:92: RuntimeWarning: invalid value encountered in double_scalars
  test = (2*((1-(read_in[0][1])**2)**.5)*read_out[0][1] + (4*(read_in[0][1]**2 - read_out[0][1]**2))**.5)/2


nan
0.5490776095565297
0.8764998967502651
0.995321045968201
0.995181677062196
0.9048539593984528
0.5409342761380433
-0.13748558659373442
nan
0.11558646280561008
0.5655891797609471
0.9005680250014754
0.8657242260864568
0.7264009035085974
0.5262479475412665
nan
nan
0.8746458543912
0.9665152374445523
0.9656618982919754
0.9282524609349242
0.5043078886752719
nan
nan
nan
0.25709957987651305
0.7853587695981037
0.7981869293901752
0.7171003257528623
0.5505165165953873
nan
nan
nan
0.8498856483249988
0.9051526470121781
0.9465790365012584
0.46497310620637633
nan
nan
nan
nan
0.6045942057069601
0.7143655422791703
0.7075684868756973
0.5250357460925703


In [6]:
threading.Thread(target=pump).start()

In [7]:
sin_u

array([ 0.00000000e+00,  6.34239197e-02,  1.26592454e-01,  1.89251244e-01,
        2.51147987e-01,  3.12033446e-01,  3.71662456e-01,  4.29794912e-01,
        4.86196736e-01,  5.40640817e-01,  5.92907929e-01,  6.42787610e-01,
        6.90079011e-01,  7.34591709e-01,  7.76146464e-01,  8.14575952e-01,
        8.49725430e-01,  8.81453363e-01,  9.09631995e-01,  9.34147860e-01,
        9.54902241e-01,  9.71811568e-01,  9.84807753e-01,  9.93838464e-01,
        9.98867339e-01,  9.99874128e-01,  9.96854776e-01,  9.89821442e-01,
        9.78802446e-01,  9.63842159e-01,  9.45000819e-01,  9.22354294e-01,
        8.95993774e-01,  8.66025404e-01,  8.32569855e-01,  7.95761841e-01,
        7.55749574e-01,  7.12694171e-01,  6.66769001e-01,  6.18158986e-01,
        5.67059864e-01,  5.13677392e-01,  4.58226522e-01,  4.00930535e-01,
        3.42020143e-01,  2.81732557e-01,  2.20310533e-01,  1.58001396e-01,
        9.50560433e-02,  3.17279335e-02, -3.17279335e-02, -9.50560433e-02,
       -1.58001396e-01, -

In [8]:
np.sin(u)

array([ 0.00000000e+00,  6.34239197e-02,  1.26592454e-01,  1.89251244e-01,
        2.51147987e-01,  3.12033446e-01,  3.71662456e-01,  4.29794912e-01,
        4.86196736e-01,  5.40640817e-01,  5.92907929e-01,  6.42787610e-01,
        6.90079011e-01,  7.34591709e-01,  7.76146464e-01,  8.14575952e-01,
        8.49725430e-01,  8.81453363e-01,  9.09631995e-01,  9.34147860e-01,
        9.54902241e-01,  9.71811568e-01,  9.84807753e-01,  9.93838464e-01,
        9.98867339e-01,  9.99874128e-01,  9.96854776e-01,  9.89821442e-01,
        9.78802446e-01,  9.63842159e-01,  9.45000819e-01,  9.22354294e-01,
        8.95993774e-01,  8.66025404e-01,  8.32569855e-01,  7.95761841e-01,
        7.55749574e-01,  7.12694171e-01,  6.66769001e-01,  6.18158986e-01,
        5.67059864e-01,  5.13677392e-01,  4.58226522e-01,  4.00930535e-01,
        3.42020143e-01,  2.81732557e-01,  2.20310533e-01,  1.58001396e-01,
        9.50560433e-02,  3.17279335e-02, -3.17279335e-02, -9.50560433e-02,
       -1.58001396e-01, -

In [9]:
theta = 2*np.arccos(qubit[0])
phi = np.log(qubit[1]/np.sin(theta/2))/(0+1j)
print(theta,phi)

(1.5780351167507587-0.12024982629376027j) (-0.0008663066372183436+0.0071868278815349525j)


In [ ]:
theta = 1/26*np.pi
I = np.cos(0)
Q = np.sin(0)
qubit2 = [1+0j,0+0j]
qubit = [0+0j,1+0j]
U = [[np.cos(theta/2)+0j,-np.sin(theta/2)+0j],[np.sin(theta/2)+0j,np.cos(theta/2)+0j]]
qubit2[0] = U[0][0]*qubit[0] + U[0][1]*qubit[1]
qubit2[1] = U[1][0]*qubit[0] + U[1][1]*qubit[1]

In [ ]:
# このセルを実行するとアニメーションが終了する
ani.event_source.stop()

In [ ]:
#このセルを実行するとアニメーションが開始する
ani.event_source.start()

In [59]:
exp_data_record

[[0.0, 0.0, (1+0j)],
 [0.0, 0.0, (1.0000000000000002+0j)],
 [0.0, 0.0, (1.0000000000000002+0j)],
 [0.0, 0.0, (1.0000000000000002+0j)],
 [0.0, 0.0, (1.0000000000000002+0j)],
 [0.0, 0.0, (1+0j)],
 [0.0, 0.0, (1+0j)],
 [0.0, 0.0, (1+0j)],
 [0.0, 0.0, (1+0j)],
 [0.0, 0.0, (1.0000000000000002+0j)],
 [0.0, 0.0, (1.0000000000000002+0j)],
 [0.0, 0.0, (1.0000000000000004+0j)],
 [0.0, 0.0, (1.0000000000000004+0j)],
 [0.0, -0.12053668025532312, (0.9927088740980546+0j)],
 [0.0, -0.23931566428755788, (0.9709418174260526+0j)],
 [0.0, -0.35460488704253584, (0.9350162426854155+0j)],
 [0.0, -0.46472317204376884, (0.8854560256532105+0j)],
 [0.0, -0.5680647467311561, (0.8229838658936571+0j)],
 [0.0, -0.6631226582407956, (0.7485107481711016+0j)],
 [0.0, -0.7485107481711016, (0.6631226582407957+0j)],
 [0.0, -0.8229838658936569, (0.5680647467311564+0j)],
 [0.0, -0.8854560256532105, (0.46472317204376895+0j)],
 [0.0, -0.9350162426854153, (0.3546048870425359+0j)],
 [0.0, -0.9709418174260527, (0.239315664287558

In [ ]:
np.arccos(0.707)*2

In [229]:
read_out

[[29, 0.3583679495453017, 0.9335804264972012]]

In [230]:
read_in

[]

In [122]:
qubit[1]

(0.7058167032059498-0.042694044965153034j)

In [ ]:
x = np.linspace(-np.pi, np.pi, 100)
y = 2*np.sin(x)

ax = fig.add_subplot(2, 2, 2)
ax.set_title('zeroed spines')
ax.plot(x, y)
ax.spines['left'].set_position('zero')
ax.spines['right'].set_color('none')
ax.spines['bottom'].set_position('zero')
ax.spines['top'].set_color('none')
ax.spines['left'].set_smart_bounds(True)
ax.spines['bottom'].set_smart_bounds(True)
ax.xaxis.set_ticks_position('bottom')
ax.yaxis.set_ticks_position('left')

# ----------------------------------------------------


def adjust_spines(ax, spines):
    for loc, spine in ax.spines.items():
        if loc in spines:
            spine.set_position(('outward', 10))  # outward by 10 points
            spine.set_smart_bounds(True)
        else:
            spine.set_color('none')  # don't draw spine

    # turn off ticks where there is no spine
    if 'left' in spines:
        ax.yaxis.set_ticks_position('left')
    else:
        # no yaxis ticks
        ax.yaxis.set_ticks([])

    if 'bottom' in spines:
        ax.xaxis.set_ticks_position('bottom')
    else:
        # no xaxis ticks
        ax.xaxis.set_ticks([])

fig = plt.figure()

x = np.linspace(0, 2*np.pi, 100)
y = 2*np.sin(x)

ax = fig.add_subplot(2, 2, 2)
ax.plot(x, y, clip_on=False)
adjust_spines(ax, [])

plt.show()

In [166]:
read_out

[[0, 0.0, 0.0],
 [1, 5.555555555555556e-05, 4.1666666666666665e-05],
 [2, 0.00022222222222222223, 0.00016666666666666666],
 [3, 0.0005000000000000001, 0.00037500000000000006],
 [4, 0.0008888888888888889, 0.0006666666666666666],
 [5, 0.001388888888888889, 0.0010416666666666667],
 [6, 0.0020000000000000005, 0.0015000000000000002],
 [7, 0.0027222222222222227, 0.002041666666666667],
 [8, 0.0035555555555555557, 0.0026666666666666666],
 [9, 0.0045, 0.003375],
 [10, 0.005555555555555556, 0.004166666666666667],
 [11, 0.0067222222222222214, 0.005041666666666666],
 [12, 0.008000000000000002, 0.006000000000000001],
 [13, 0.009388888888888891, 0.0070416666666666666],
 [14, 0.01088888888888889, 0.008166666666666668],
 [15, 0.0125, 0.009375],
 [16, 0.014222222222222223, 0.010666666666666666],
 [17, 0.016055555555555556, 0.012041666666666664],
 [18, 0.018, 0.0135],
 [19, 0.020055555555555556, 0.015041666666666665],
 [20, 0.022222222222222223, 0.016666666666666666],
 [21, 0.024499999999999997, 0.01837

In [ ]:
def apply_gate(phi,t):
    I = np.cos(phi)
    Q = np.sin(phi)
    qubit2 = [1+0j,0+0j]
    theta = np.pi * t/26
    U = [[np.cos(theta/2)+0j,-Q*np.sin(theta/2)-I*(np.sin(theta/2))*1j],[Q*np.sin(theta/2)-I*(np.sin(theta/2))*1j,np.cos(theta/2)+0j]]
    qubit2[0] = U[0][0]*qubit[0] + U[0][1]*qubit[1]
    qubit2[1] = U[1][0]*qubit[0] + U[1][1]*qubit[1]
    return qubit2

In [ ]:
for i in range(13):
    qubit = apply_gate(0,4)
    print(qubit)

In [ ]:
theta = np.pi * 1/26
U = [[np.cos(theta/2)+0j,-Q*np.sin(theta/2)-I*(np.sin(theta/2))*1j],[Q*np.sin(theta/2)-I*(np.sin(theta/2))*1j,np.cos(theta/2)+0j]]
def product(U):
    U2=[[0,0],[0,0]]
    for i in range(2):
        for j in range(2):
            U2[i][j] = U[i][j] * U[j][i] 
    return U2
for i in range(13):
    U = product(U)
    print(product(U))

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D
from mpl_toolkits import mplot3d
import matplotlib.animation as animation
import time
import threading

exp_data_record = []

def plot_dat(qubit):
    #実験データを角度φとΘに変換
    theta = 2*np.arccos(qubit[0])
    if qubit[1] == 0:
        phi = 0
    else:
        phi = np.log(qubit[1]/np.sin(theta/2))/(0+1j)
    #角度をxyz座標に変換
    exp_data_record.append([np.sin(theta)*np.cos(phi),np.sin(theta)*np.sin(phi),np.cos(theta)])

In [ ]:
%matplotlib widget


#実験結果をプロット
def update(i):
    #time.sleep(1)
    ax3.clear()
    ax3.plot_surface(x, y, z,  rstride=4, cstride=4, color='lightblue', linewidth=0, alpha=0.2)

    ax3.plot(np.sin(u),np.cos(u),0,color='gray',linewidth=1.2)
    ax3.plot(np.linspace(0,0,100),np.sin(u),np.cos(u),color='gray',linewidth=1.2)
    ax3.plot(np.sin(u),np.linspace(0,0,100),np.cos(u),color='gray',linewidth=.5)

    for i in range(-4,5,1):
        if i!=0:
            d = .25 * i
        s = ((1-d**2)**.5)
        ax3.plot(np.sin(u)*s,np.cos(u)*s,d,color='gray',linewidth=.3)
        ax3.plot(np.linspace(d,d,100),np.sin(u)*s,np.cos(u)*s,color='gray',linewidth=.3)
        #ax.plot(np.sin(u)*s,np.linspace(d,d,100),np.cos(u)*s,color='gray',linewidth=.3)
    ax3.plot(exp_data_record[-1][0], exp_data_record[-1][1], exp_data_record[-1][2], "o", c="blue")
    
#x.scatter(exp_data_record[-1][0], exp_data_record[-1][1], exp_data_record[-1][2], "o", c="blue")

#アニメーション
ani = animation.FuncAnimation(fig, update, interval=20, blit=True)
   
plt.show()

In [ ]:
#実験データを取得するとみなすダミー
def get_dat():
    for i in range(26):
        qubit = [1+0j,0+0j]
        qubit = apply_gate(qubit,i)
        plot_dat(qubit)
        time.sleep(0.2)

threading.Thread(target=get_dat).start()

In [ ]:
exp_data_record

In [134]:
def plot_data(input_wave):
    time = input_wave[0]
    i = input_wave[1]
    q = input_wave[2]
    ctrl_in.append([time,i,q])
            
def simple_pulse(event):
    for i in range(53):
        if event.is_set():
            break
        if (i>=0 and i<52):
            if(i>=0 and i<26):    
                phi = 0
            else:
                phi = np.pi/2
            a = np.sin(phi+(i/26)*np.pi)
            b = np.cos(phi+(i/26)*np.pi)
            qubit = apply_gate(phi,1)
        else:
            a = b = 0
        input_wave = [i, a, b]
        plot_data(input_wave)
        #qubit = apply_gate(0,1) #RX-gate
        #qubit = apply_gate(np.pi/2,1) #RY-gate
        time.sleep(0.05)

In [11]:
import matplotlib.pyplot as plt
import numpy as np
from matplotlib.animation import FuncAnimation
import collections
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D
from mpl_toolkits import mplot3d
import time
import threading
    
%matplotlib tk

exp_data_record = []
qubit_h = []
qubit = [1+0j,0+0j]

# function to update the data
ctrl_in = []
read_in = []
read_out = []
pump_in = []
theta = 0
theta1 = 0
signal_range = 0.5
ms = 0 #measurement

#fig = plt.figure()
fig = plt.figure(figsize=(10,8), facecolor='#DEDEDE', tight_layout=True)

def my_function(i):
    global theta1, signal_range, read_in, read_out, theta, m
    # input control
    
    input_sys_i.popleft()
    input_sys_q.popleft()
    if len(ctrl_in)>1:
        input_sys_i.append(ctrl_in[-1][1])
        input_sys_q.append(ctrl_in[-1][2])
    else:
        input_sys_i.append(0.0)
        input_sys_q.append(0.0)

    # clear axis
    ax1.cla()
    
    ax1.set_title("Input Control Wave")
    # plot input1
    ax1.plot(input_sys_i,color="blue")
    ax1.scatter(len(input_sys_i)-1, input_sys_i[-1],color="blue")
    #ax1.text(len(input_sys_i)-1, input_sys_i[-1]+2, "{}%".format(input_sys_i[-1]))
    ax1.set_ylim(-1,1)
    
    ax1.plot(input_sys_q,color="red")
    ax1.scatter(len(input_sys_q)-1, input_sys_q[-1],color="red")
    #ax1.text(len(input_sys_q)-1, input_sys_q[-1]+2, "{}%".format(input_sys_q[-1]))

# start collections with zeros
input_sys_i = collections.deque(np.zeros(100))
input_sys_q = collections.deque(np.zeros(100))

# define and adjust figure
gs = fig.add_gridspec(4,4)
ax1 = fig.add_subplot(gs[0, 0:2], facecolor="white")  

# animate
ani = FuncAnimation(fig, my_function, interval=50)
plt.show()

In [193]:
import matplotlib.pyplot as plt
from mpl_toolkits.axisartist.axislines import Subplot
   
  
fig = plt.figure(figsize=(10,8), facecolor='#DEDEDE', tight_layout=True)
   
ax = Subplot(fig, 222)
fig.add_subplot(ax)
   
ax.axis["left"].set_visible(False)
ax.axis["bottom"].set_visible(False)
  
fig.suptitle('matplotlib.figure.Figure.add_subplot() \
function Example\n\n', fontweight ="bold")

plt.show()

In [148]:
import cv2

img = 50 * np.ones(shape=[256, 256, 3], dtype=np.uint8)
print(img)

[[[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 ...

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]]


In [144]:
test[-1:]

[3]

In [116]:
r = 3.333
type(r)

float